$axure.loadCurrentPage({
  "url":"评论回复.html",
  "generationDate":new Date(1392634063330.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2f47f2a4d2424d378263fb4b1a28c837",
    "type":"Axure:Page",
    "name":"评论回复",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9937fb62330d4f0a8979ab55ffc322e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df16de31573544c7b8b51c7ee2b53f33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"35fcdd903bd941f0ae3db34c707e2368",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":1},
            "size":{
              "width":319,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ec24a855d3342298defc683d03781e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":1},
                "size":{
                  "width":319,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"ef805b4942264f55bb15b2ff11502fb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5057ecc73d404c15bcb92fbe4eb0344d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u106.png"}},
{
          "id":"184552e4be6f4fac940b1ec900489b2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":34},
            "size":{
              "width":37,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f1944a2a1e541b09fc08a6aa2893da5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":34},
                "size":{
                  "width":37,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7b2695e8f09487f837571230db65ea6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":18,
              "y":77},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db704084f34b4fd49fb82cefa358a1bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":18,
                  "y":77},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c21062c021db4d6891bc2cd577191fab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":283,
              "y":34},
            "size":{
              "width":37,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f854734e456403589eaf403423fc0d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":283,
                  "y":34},
                "size":{
                  "width":37,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"235f1cadd6f14178b1dbcf677f91ff33",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":77},
            "size":{
              "width":10,
              "height":20},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/评论回复/u12_line.png"}},
{
          "id":"d598c4e98e9341c5b2dce9d16422b362",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":1,
              "y":265},
            "size":{
              "width":320,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"084bd61ec6934c389ec09883099524c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":1,
                  "y":265},
                "size":{
                  "width":320,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评论回复/u13.png"}},
{
          "id":"5388846262a441529b52c965a4d4efc0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":0,
              "y":230},
            "size":{
              "width":320,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff44197cf64249b5b0de988a2a053f14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":0,
                  "y":230},
                "size":{
                  "width":320,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评论回复/u15.png"}},
{
          "id":"bec4863375c34e7cbcb6a7e4ba39844f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":234},
            "size":{
              "width":37,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbae1ab44efd412991eb386c85cac4e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":234},
                "size":{
                  "width":37,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评论回复/u17.png"}},
{
          "id":"66766cac85bf4387aa368e1d8117eb76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":234},
            "size":{
              "width":37,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74fdae2095fc4ad0b3dd8c005717cfe8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":234},
                "size":{
                  "width":37,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评论回复/u17.png"}},
{
          "id":"571e24b9ce094039a43ed47bfb12d701",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":179,
              "y":234},
            "size":{
              "width":37,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"470bd10bf1314431b67ab2e95ec003b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":179,
                  "y":234},
                "size":{
                  "width":37,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评论回复/u17.png"}},
{
          "id":"1fa9dadbc2224cd8b61944bc6345a58b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":234},
            "size":{
              "width":37,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cce7a4e281804b4c8739d2ed411daa80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":234},
                "size":{
                  "width":37,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评论回复/u17.png"}},
{
          "id":"819731d108874eca81a303fbfe42d654",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":80},
            "size":{
              "width":260,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/家庭首页/u102_end.png",
            "line~":"images/评论回复/u25_line.png"}},
{
          "id":"496b324e510a4541addaa236ed485e9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":77},
            "size":{
              "width":363,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83ef365cbfec4974ac80193b5bbac948",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":77},
                "size":{
                  "width":363,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9937fb62330d4f0a8979ab55ffc322e0":{
      "scriptId":"u0"},
    "df16de31573544c7b8b51c7ee2b53f33":{
      "scriptId":"u1"},
    "35fcdd903bd941f0ae3db34c707e2368":{
      "scriptId":"u2"},
    "9ec24a855d3342298defc683d03781e2":{
      "scriptId":"u3"},
    "ef805b4942264f55bb15b2ff11502fb5":{
      "scriptId":"u4"},
    "5057ecc73d404c15bcb92fbe4eb0344d":{
      "scriptId":"u5"},
    "184552e4be6f4fac940b1ec900489b2e":{
      "scriptId":"u6"},
    "0f1944a2a1e541b09fc08a6aa2893da5":{
      "scriptId":"u7"},
    "c7b2695e8f09487f837571230db65ea6":{
      "scriptId":"u8"},
    "db704084f34b4fd49fb82cefa358a1bc":{
      "scriptId":"u9"},
    "c21062c021db4d6891bc2cd577191fab":{
      "scriptId":"u10"},
    "8f854734e456403589eaf403423fc0d9":{
      "scriptId":"u11"},
    "235f1cadd6f14178b1dbcf677f91ff33":{
      "scriptId":"u12"},
    "d598c4e98e9341c5b2dce9d16422b362":{
      "scriptId":"u13"},
    "084bd61ec6934c389ec09883099524c4":{
      "scriptId":"u14"},
    "5388846262a441529b52c965a4d4efc0":{
      "scriptId":"u15"},
    "ff44197cf64249b5b0de988a2a053f14":{
      "scriptId":"u16"},
    "bec4863375c34e7cbcb6a7e4ba39844f":{
      "scriptId":"u17"},
    "cbae1ab44efd412991eb386c85cac4e0":{
      "scriptId":"u18"},
    "66766cac85bf4387aa368e1d8117eb76":{
      "scriptId":"u19"},
    "74fdae2095fc4ad0b3dd8c005717cfe8":{
      "scriptId":"u20"},
    "571e24b9ce094039a43ed47bfb12d701":{
      "scriptId":"u21"},
    "470bd10bf1314431b67ab2e95ec003b9":{
      "scriptId":"u22"},
    "1fa9dadbc2224cd8b61944bc6345a58b":{
      "scriptId":"u23"},
    "cce7a4e281804b4c8739d2ed411daa80":{
      "scriptId":"u24"},
    "819731d108874eca81a303fbfe42d654":{
      "scriptId":"u25"},
    "496b324e510a4541addaa236ed485e9e":{
      "scriptId":"u26"},
    "83ef365cbfec4974ac80193b5bbac948":{
      "scriptId":"u27"}}});