$axure.loadCurrentPage({
  "url":"拉钩盒子.html",
  "generationDate":new Date(1392634064334.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d9fde621b15940aebf8386d0139840d2",
    "type":"Axure:Page",
    "name":"拉钩盒子",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a42b820727d54c21bf3b17ca213e15e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":0},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57340341d84b475989ef52a45f18b31c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":0},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"2aacc8dcd5d74886b31c458fae2c4cf4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":1},
            "size":{
              "width":319,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b967c13de68d49beace1f2798dcd37d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2,
                  "y":1},
                "size":{
                  "width":319,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"2a0c41b9970b448baf60338994758f9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":1,
              "y":20},
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e07d4582d474e75a649adf1a72d5eee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":1,
                  "y":20},
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u106.png"}},
{
          "id":"afbdb09fb5884947910b5e07e674e4b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":34},
            "size":{
              "width":37,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d16fc36e5c3a40b488006481fe3c26b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":34},
                "size":{
                  "width":37,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3444b1f4e6c4840afa7f0439b9fce6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-2,
              "y":26},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c27b0b2a91684bb7ac9adaaf60ff1fd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-2,
                  "y":26},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u245.png"}},
{
          "id":"58e4e48bd3194f0aa72489bc87806b06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":254,
              "y":36},
            "size":{
              "width":60,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ab36f24240842cab1907c272f90ba9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":254,
                  "y":36},
                "size":{
                  "width":60,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5da2f99c1824174b537c8ef9a4a8f48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":64},
            "size":{
              "width":320,
              "height":136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67a19ea9a30a48b9bd9451c90239016c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":64},
                "size":{
                  "width":320,
                  "height":136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u12.png"}},
{
          "id":"95d4716e46db4a26bc64b8fae167929c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x5E000000},
            "location":{
              "x":1,
              "y":170},
            "size":{
              "width":320,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b9bc3a0f9fd4c9b972e173772bcdf0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x5E000000},
                "location":{
                  "x":1,
                  "y":170},
                "size":{
                  "width":320,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u14.png"}},
{
          "id":"73f1575ac845458ba914c75d107ef637",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":8,
              "y":177},
            "size":{
              "width":177,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc9e882b75b74914a19679e928215b68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":8,
                  "y":177},
                "size":{
                  "width":177,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b06ce6229554b9c87eea7095ad4d632",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1,
              "y":200},
            "size":{
              "width":160,
              "height":79}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ac6dfed17024969a734c66138f9b349",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1,
                  "y":200},
                "size":{
                  "width":160,
                  "height":79}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u18.png"}},
{
          "id":"68604a3e514c431981c9fe1a46804665",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":161,
              "y":200},
            "size":{
              "width":160,
              "height":79}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d188f4699d154a219a173a2e50cdab98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":161,
                  "y":200},
                "size":{
                  "width":160,
                  "height":79}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u18.png"}},
{
          "id":"395aa463d50643619e71af43deb2b8ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1,
              "y":279},
            "size":{
              "width":320,
              "height":79}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1ae3a799d524c13904edab79874cd76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1,
                  "y":279},
                "size":{
                  "width":320,
                  "height":79}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u22.png"}},
{
          "id":"ab6477bb6d81444d8629cac2dd0be228",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":1,
              "y":358},
            "size":{
              "width":160,
              "height":79}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9152b59c5084c1dab7e0a856159772b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":1,
                  "y":358},
                "size":{
                  "width":160,
                  "height":79}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u18.png"}},
{
          "id":"56aec733c1d14e489e29cdf6f3d1651e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":161,
              "y":358},
            "size":{
              "width":160,
              "height":79}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fc2771b9927482998aa4415f336e5a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":161,
                  "y":358},
                "size":{
                  "width":160,
                  "height":79}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u18.png"}},
{
          "id":"32efde78d94944559418aa73a1b1418c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":354,
              "y":0},
            "size":{
              "width":320,
              "height":530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eff96d31907b4ab8a9f38032b93c98cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":354,
                  "y":0},
                "size":{
                  "width":320,
                  "height":530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/家庭详情/u0.png"}},
{
          "id":"64e227a519394c93add277e1b754b444",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":355,
              "y":1},
            "size":{
              "width":319,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1443d70fcb9049a484c59e7de951d9b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":355,
                  "y":1},
                "size":{
                  "width":319,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"f99143ec97b44da1b50de52c73f8175a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":354,
              "y":20},
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec8a35347a14498a53c7eeef2af9119",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":354,
                  "y":20},
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u106.png"}},
{
          "id":"a2c697365f294eac9953390743c4cacb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":374,
              "y":34},
            "size":{
              "width":37,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70896e2115984708bac633f9598ba26a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":374,
                  "y":34},
                "size":{
                  "width":37,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ef54c5696344dd68fb10e3952016375",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":26},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed8cb98350854506a8d0003178c1ec51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":351,
                  "y":26},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u245.png"}},
{
          "id":"adad50a6bf3642468fcb35006f9d1e80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":607,
              "y":36},
            "size":{
              "width":60,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"430be3cca7d0425b8fb9b3a4f555bc0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":607,
                  "y":36},
                "size":{
                  "width":60,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"840c50d725b443e8b2c445452fda541a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":74},
            "size":{
              "width":299,
              "height":126}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b204f357a3c14028a70e614ad47efa96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":74},
                "size":{
                  "width":299,
                  "height":126}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u40.png"}},
{
          "id":"4eda8dc830d5475f9f79c50d95514633",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x5E000000},
            "location":{
              "x":365,
              "y":172},
            "size":{
              "width":299,
              "height":28},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51018eec33ae47a89144ddb0fb3ad5b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x5E000000},
                "location":{
                  "x":365,
                  "y":172},
                "size":{
                  "width":299,
                  "height":28},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u42.png"}},
{
          "id":"18d8b4a27ca34995b2ceacb6e5b6cb9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":378,
              "y":177},
            "size":{
              "width":286,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"699e1ce46c8b40bcb87e4946c7aedda7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":378,
                  "y":177},
                "size":{
                  "width":286,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab89884367da45d89c1b83dd9bcd2cab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":210},
            "size":{
              "width":299,
              "height":148}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0df2244771c24b88aaebdb26627db9ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":210},
                "size":{
                  "width":299,
                  "height":148}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u46.png"}},
{
          "id":"a0fe957c819f47679cc95b8e885b4d9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x5E000000},
            "location":{
              "x":365,
              "y":325},
            "size":{
              "width":299,
              "height":33},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c373ad4e261429d9bbf510ae769d823",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x5E000000},
                "location":{
                  "x":365,
                  "y":325},
                "size":{
                  "width":299,
                  "height":33},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u48.png"}},
{
          "id":"b3e8aacf04394f918f8657769573dcd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":378,
              "y":331},
            "size":{
              "width":286,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e844ba9b85cb41319980901fb266ef32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":378,
                  "y":331},
                "size":{
                  "width":286,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77bed7b634e74d2bac9e96bd0266214e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":368},
            "size":{
              "width":299,
              "height":142}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b088dab8c2104d489fd90235fdd86079",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":368},
                "size":{
                  "width":299,
                  "height":142}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u52.png"}},
{
          "id":"7df8b2a2c3bb4fb5bb69d4db1aad2003",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x5E000000},
            "location":{
              "x":365,
              "y":484},
            "size":{
              "width":299,
              "height":26},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6ec26cebd5b4734ad1451ccb7a2d8e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x5E000000},
                "location":{
                  "x":365,
                  "y":484},
                "size":{
                  "width":299,
                  "height":26},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/拉钩盒子/u54.png"}},
{
          "id":"73de776f10d44ad495d087e14cf8f4f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":378,
              "y":489},
            "size":{
              "width":286,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2f84bde0fab4e9d9f35557e20cee9bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":378,
                  "y":489},
                "size":{
                  "width":286,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12e4446bb8954c9e9692a7670618925f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":554},
            "size":{
              "width":248,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c099a080015a4e6ab4a1fc19d4622033",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":43,
                  "y":554},
                "size":{
                  "width":248,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7e2699a1eb04f94ba0f564f26f4b74e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":554},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cec48977d10474d9960e5866a86e4e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":554},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a42b820727d54c21bf3b17ca213e15e3":{
      "scriptId":"u0"},
    "57340341d84b475989ef52a45f18b31c":{
      "scriptId":"u1"},
    "2aacc8dcd5d74886b31c458fae2c4cf4":{
      "scriptId":"u2"},
    "b967c13de68d49beace1f2798dcd37d5":{
      "scriptId":"u3"},
    "2a0c41b9970b448baf60338994758f9c":{
      "scriptId":"u4"},
    "7e07d4582d474e75a649adf1a72d5eee":{
      "scriptId":"u5"},
    "afbdb09fb5884947910b5e07e674e4b1":{
      "scriptId":"u6"},
    "d16fc36e5c3a40b488006481fe3c26b9":{
      "scriptId":"u7"},
    "c3444b1f4e6c4840afa7f0439b9fce6a":{
      "scriptId":"u8"},
    "c27b0b2a91684bb7ac9adaaf60ff1fd1":{
      "scriptId":"u9"},
    "58e4e48bd3194f0aa72489bc87806b06":{
      "scriptId":"u10"},
    "7ab36f24240842cab1907c272f90ba9a":{
      "scriptId":"u11"},
    "d5da2f99c1824174b537c8ef9a4a8f48":{
      "scriptId":"u12"},
    "67a19ea9a30a48b9bd9451c90239016c":{
      "scriptId":"u13"},
    "95d4716e46db4a26bc64b8fae167929c":{
      "scriptId":"u14"},
    "5b9bc3a0f9fd4c9b972e173772bcdf0b":{
      "scriptId":"u15"},
    "73f1575ac845458ba914c75d107ef637":{
      "scriptId":"u16"},
    "cc9e882b75b74914a19679e928215b68":{
      "scriptId":"u17"},
    "1b06ce6229554b9c87eea7095ad4d632":{
      "scriptId":"u18"},
    "9ac6dfed17024969a734c66138f9b349":{
      "scriptId":"u19"},
    "68604a3e514c431981c9fe1a46804665":{
      "scriptId":"u20"},
    "d188f4699d154a219a173a2e50cdab98":{
      "scriptId":"u21"},
    "395aa463d50643619e71af43deb2b8ea":{
      "scriptId":"u22"},
    "a1ae3a799d524c13904edab79874cd76":{
      "scriptId":"u23"},
    "ab6477bb6d81444d8629cac2dd0be228":{
      "scriptId":"u24"},
    "b9152b59c5084c1dab7e0a856159772b":{
      "scriptId":"u25"},
    "56aec733c1d14e489e29cdf6f3d1651e":{
      "scriptId":"u26"},
    "3fc2771b9927482998aa4415f336e5a9":{
      "scriptId":"u27"},
    "32efde78d94944559418aa73a1b1418c":{
      "scriptId":"u28"},
    "eff96d31907b4ab8a9f38032b93c98cc":{
      "scriptId":"u29"},
    "64e227a519394c93add277e1b754b444":{
      "scriptId":"u30"},
    "1443d70fcb9049a484c59e7de951d9b2":{
      "scriptId":"u31"},
    "f99143ec97b44da1b50de52c73f8175a":{
      "scriptId":"u32"},
    "0ec8a35347a14498a53c7eeef2af9119":{
      "scriptId":"u33"},
    "a2c697365f294eac9953390743c4cacb":{
      "scriptId":"u34"},
    "70896e2115984708bac633f9598ba26a":{
      "scriptId":"u35"},
    "6ef54c5696344dd68fb10e3952016375":{
      "scriptId":"u36"},
    "ed8cb98350854506a8d0003178c1ec51":{
      "scriptId":"u37"},
    "adad50a6bf3642468fcb35006f9d1e80":{
      "scriptId":"u38"},
    "430be3cca7d0425b8fb9b3a4f555bc0e":{
      "scriptId":"u39"},
    "840c50d725b443e8b2c445452fda541a":{
      "scriptId":"u40"},
    "b204f357a3c14028a70e614ad47efa96":{
      "scriptId":"u41"},
    "4eda8dc830d5475f9f79c50d95514633":{
      "scriptId":"u42"},
    "51018eec33ae47a89144ddb0fb3ad5b3":{
      "scriptId":"u43"},
    "18d8b4a27ca34995b2ceacb6e5b6cb9c":{
      "scriptId":"u44"},
    "699e1ce46c8b40bcb87e4946c7aedda7":{
      "scriptId":"u45"},
    "ab89884367da45d89c1b83dd9bcd2cab":{
      "scriptId":"u46"},
    "0df2244771c24b88aaebdb26627db9ef":{
      "scriptId":"u47"},
    "a0fe957c819f47679cc95b8e885b4d9c":{
      "scriptId":"u48"},
    "0c373ad4e261429d9bbf510ae769d823":{
      "scriptId":"u49"},
    "b3e8aacf04394f918f8657769573dcd5":{
      "scriptId":"u50"},
    "e844ba9b85cb41319980901fb266ef32":{
      "scriptId":"u51"},
    "77bed7b634e74d2bac9e96bd0266214e":{
      "scriptId":"u52"},
    "b088dab8c2104d489fd90235fdd86079":{
      "scriptId":"u53"},
    "7df8b2a2c3bb4fb5bb69d4db1aad2003":{
      "scriptId":"u54"},
    "e6ec26cebd5b4734ad1451ccb7a2d8e7":{
      "scriptId":"u55"},
    "73de776f10d44ad495d087e14cf8f4f7":{
      "scriptId":"u56"},
    "a2f84bde0fab4e9d9f35557e20cee9bd":{
      "scriptId":"u57"},
    "12e4446bb8954c9e9692a7670618925f":{
      "scriptId":"u58"},
    "c099a080015a4e6ab4a1fc19d4622033":{
      "scriptId":"u59"},
    "a7e2699a1eb04f94ba0f564f26f4b74e":{
      "scriptId":"u60"},
    "1cec48977d10474d9960e5866a86e4e7":{
      "scriptId":"u61"}}});