$axure.loadCurrentPage({
  "url":"设置.html",
  "generationDate":new Date(1392634061432.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"30dbdc4802524d6db16c9e462bd151f5",
    "type":"Axure:Page",
    "name":"设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6a85e1d376204cfe9e49f647f0d7c9b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":490}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b329fd61a3c4409a6d226171922d8a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":490}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设置/u0.png"}},
{
          "id":"2a996ae5e93e45d6b174a99d481ff3c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":1},
            "size":{
              "width":319,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d29d2ff20884cf1be2bef86be53b993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":1},
                "size":{
                  "width":319,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"e9d87c6c0e944ec99c72d6cf8d9337de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07308eaf639b4bbd9cf980786c3d74be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u106.png"}},
{
          "id":"b3d956f1cf7647209846544c3d64fbff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":173},
            "size":{
              "width":302,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4f188d930054e5498f76c54b15ee90d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":173},
                "size":{
                  "width":302,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u108.png"}},
{
          "id":"0e756d58266d4116a3ac67abd88681d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":188},
            "size":{
              "width":97,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f67ee0014b0a461285d74d82cf913fef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":188},
                "size":{
                  "width":97,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e1e643abe7645ccb0f6dd0c375c2ee0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":74},
            "size":{
              "width":302,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73e8b782bc744c4fbe9f962dc87561b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":74},
                "size":{
                  "width":302,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u112.png"}},
{
          "id":"78f16ed48b3f4f18ad9d946b5a8c1497",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":86},
            "size":{
              "width":149,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0fe1f72758f4c958e7330f420779c0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":86},
                "size":{
                  "width":149,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a3cc9f1aca24fd2b7d79350aad7914f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":9,
              "y":133},
            "size":{
              "width":302,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05502fee244b4b0eb81db38fc610cda5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":9,
                  "y":133},
                "size":{
                  "width":302,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u112.png"}},
{
          "id":"c731f7ab58c849f990b8c6c043989d3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":145},
            "size":{
              "width":149,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5efe07d37d9e4e4c8323d20e5209f936",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":145},
                "size":{
                  "width":149,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40a4be899b194a398b4e6492137daa11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":281},
            "size":{
              "width":302,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a91113af72249d09cec116b4e4f1a72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":281},
                "size":{
                  "width":302,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u108.png"}},
{
          "id":"ec08ed720fd64045948692ac280613bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":296},
            "size":{
              "width":97,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d4448808b78440cb80ddcb95cb3f861",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":296},
                "size":{
                  "width":97,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"404ebe5b58734b0eb7a5c16570466cb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "stateStyles":{
              "mouseDown":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}}},
            "location":{
              "x":9,
              "y":241},
            "size":{
              "width":302,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc800dea4b0e43e8ae96762223710db8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "stateStyles":{
                  "mouseDown":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0000FF}}},
                "location":{
                  "x":9,
                  "y":241},
                "size":{
                  "width":302,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u112.png",
            "mouseDown~":"images/首页/u124_mouseDown.png"}},
{
          "id":"006e91e8e52948438bee9f02d138700e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":253},
            "size":{
              "width":71,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd00df9b2bd24dc8a8cfa0634c3420ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":253},
                "size":{
                  "width":71,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b822e31a9ca946f393b7d1a6fe18fc0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":433},
            "size":{
              "width":302,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfe30f761a3d4258934d1beaf1df28fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":9,
                  "y":433},
                "size":{
                  "width":302,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u108.png"}},
{
          "id":"5db4333bb22f43e3abf11524c68416b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":448},
            "size":{
              "width":97,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d4fe6e16ee54c2a997806196cfa1f78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":448},
                "size":{
                  "width":97,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aaf63d03e8fa43b5ae59408666bfc5c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":9,
              "y":393},
            "size":{
              "width":302,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"107225edb31e478d946c998569db1dd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":9,
                  "y":393},
                "size":{
                  "width":302,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u112.png"}},
{
          "id":"5ea9a0733a9f46bfbc6120d9abf88564",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":405},
            "size":{
              "width":149,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c015937a10c4dd1bffc685d7ca46cf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":405},
                "size":{
                  "width":149,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d48365eb511454fa5769398fe8a8371",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":81},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0986d1ad969c40f6bed8825891b56a83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":81},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"6a3b4e8dd9884049987a1508e767c93c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":140},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"868a7195536c474eac5e08366d879aae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":140},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"33b37583479143d08aa18c2db70fd579",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":184},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbbd73a95cee48b7bd7ca1c943c3c772",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":184},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"96aa96f465af4b139999383adcc6c4ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":248},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87651e1a8a904be19919b086cf25bd3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":248},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"0cfc5b99b03d40338b8f604be50dcd4d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":291},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd662f8c6bcd409b8dc004ba577a688a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":291},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"bd2429ccecc44f7183c8a0798d51975a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":400},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfc40b96dde9481098f4f7b1b456018a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":400},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"f5da25bf3bd445489ef45441621aa98f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":444},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e49a1f4ed5e540e8b2df118b5a6fd271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":444},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"a4c7a569bce547c39f47c1ddb76bc543",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "location":{
              "x":336,
              "y":20},
            "size":{
              "width":150,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de511500b5aa49a2a59b1fd87629fb8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "location":{
                  "x":336,
                  "y":20},
                "size":{
                  "width":150,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eee6769e07284298b1f7f658b86ef5b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":59},
            "size":{
              "width":223,
              "height":32},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5bb7a98d3254316a69d3dd301357c82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":59},
                "size":{
                  "width":223,
                  "height":32},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e83f46de35bc4170a5b7918261f9e49d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":9,
              "y":326},
            "size":{
              "width":302,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32be16f225bc498a80a24c7dc05231e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":9,
                  "y":326},
                "size":{
                  "width":302,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u108.png"}},
{
          "id":"c79617a78e4f4a939d59d2f4e57e5a15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":341},
            "size":{
              "width":97,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1febaa876a84671a4cdba3c6df7ff91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":341},
                "size":{
                  "width":97,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a93c8ccbf06944efb7b3cd31d67169f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":341},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9a75c0a758548dbb3cc244525444a88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":341},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"c711b641707f4eb2a8eebd639358a716",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":4,
              "y":318},
            "size":{
              "width":311,
              "height":62},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76e2c32170fc4ce5958ecb078c902fdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":4,
                  "y":318},
                "size":{
                  "width":311,
                  "height":62},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 更换皮肤",
                      "target":{
                        "targetType":"page",
                        "url":"更换皮肤.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/设置/u58.png"}},
{
          "id":"e6dc5a69e3614e6dabe8dc2ebf154bbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":24},
            "size":{
              "width":35,
              "height":35},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5fbbd9f1a204eab955aabb2c72aa5e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":24},
                "size":{
                  "width":35,
                  "height":35},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u98.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6a85e1d376204cfe9e49f647f0d7c9b3":{
      "scriptId":"u0"},
    "6b329fd61a3c4409a6d226171922d8a5":{
      "scriptId":"u1"},
    "2a996ae5e93e45d6b174a99d481ff3c0":{
      "scriptId":"u2"},
    "0d29d2ff20884cf1be2bef86be53b993":{
      "scriptId":"u3"},
    "e9d87c6c0e944ec99c72d6cf8d9337de":{
      "scriptId":"u4"},
    "07308eaf639b4bbd9cf980786c3d74be":{
      "scriptId":"u5"},
    "b3d956f1cf7647209846544c3d64fbff":{
      "scriptId":"u6"},
    "c4f188d930054e5498f76c54b15ee90d":{
      "scriptId":"u7"},
    "0e756d58266d4116a3ac67abd88681d3":{
      "scriptId":"u8"},
    "f67ee0014b0a461285d74d82cf913fef":{
      "scriptId":"u9"},
    "4e1e643abe7645ccb0f6dd0c375c2ee0":{
      "scriptId":"u10"},
    "73e8b782bc744c4fbe9f962dc87561b0":{
      "scriptId":"u11"},
    "78f16ed48b3f4f18ad9d946b5a8c1497":{
      "scriptId":"u12"},
    "e0fe1f72758f4c958e7330f420779c0c":{
      "scriptId":"u13"},
    "2a3cc9f1aca24fd2b7d79350aad7914f":{
      "scriptId":"u14"},
    "05502fee244b4b0eb81db38fc610cda5":{
      "scriptId":"u15"},
    "c731f7ab58c849f990b8c6c043989d3b":{
      "scriptId":"u16"},
    "5efe07d37d9e4e4c8323d20e5209f936":{
      "scriptId":"u17"},
    "40a4be899b194a398b4e6492137daa11":{
      "scriptId":"u18"},
    "9a91113af72249d09cec116b4e4f1a72":{
      "scriptId":"u19"},
    "ec08ed720fd64045948692ac280613bd":{
      "scriptId":"u20"},
    "4d4448808b78440cb80ddcb95cb3f861":{
      "scriptId":"u21"},
    "404ebe5b58734b0eb7a5c16570466cb6":{
      "scriptId":"u22"},
    "dc800dea4b0e43e8ae96762223710db8":{
      "scriptId":"u23"},
    "006e91e8e52948438bee9f02d138700e":{
      "scriptId":"u24"},
    "fd00df9b2bd24dc8a8cfa0634c3420ed":{
      "scriptId":"u25"},
    "b822e31a9ca946f393b7d1a6fe18fc0f":{
      "scriptId":"u26"},
    "bfe30f761a3d4258934d1beaf1df28fd":{
      "scriptId":"u27"},
    "5db4333bb22f43e3abf11524c68416b4":{
      "scriptId":"u28"},
    "0d4fe6e16ee54c2a997806196cfa1f78":{
      "scriptId":"u29"},
    "aaf63d03e8fa43b5ae59408666bfc5c8":{
      "scriptId":"u30"},
    "107225edb31e478d946c998569db1dd5":{
      "scriptId":"u31"},
    "5ea9a0733a9f46bfbc6120d9abf88564":{
      "scriptId":"u32"},
    "7c015937a10c4dd1bffc685d7ca46cf3":{
      "scriptId":"u33"},
    "1d48365eb511454fa5769398fe8a8371":{
      "scriptId":"u34"},
    "0986d1ad969c40f6bed8825891b56a83":{
      "scriptId":"u35"},
    "6a3b4e8dd9884049987a1508e767c93c":{
      "scriptId":"u36"},
    "868a7195536c474eac5e08366d879aae":{
      "scriptId":"u37"},
    "33b37583479143d08aa18c2db70fd579":{
      "scriptId":"u38"},
    "fbbd73a95cee48b7bd7ca1c943c3c772":{
      "scriptId":"u39"},
    "96aa96f465af4b139999383adcc6c4ef":{
      "scriptId":"u40"},
    "87651e1a8a904be19919b086cf25bd3e":{
      "scriptId":"u41"},
    "0cfc5b99b03d40338b8f604be50dcd4d":{
      "scriptId":"u42"},
    "dd662f8c6bcd409b8dc004ba577a688a":{
      "scriptId":"u43"},
    "bd2429ccecc44f7183c8a0798d51975a":{
      "scriptId":"u44"},
    "bfc40b96dde9481098f4f7b1b456018a":{
      "scriptId":"u45"},
    "f5da25bf3bd445489ef45441621aa98f":{
      "scriptId":"u46"},
    "e49a1f4ed5e540e8b2df118b5a6fd271":{
      "scriptId":"u47"},
    "a4c7a569bce547c39f47c1ddb76bc543":{
      "scriptId":"u48"},
    "de511500b5aa49a2a59b1fd87629fb8c":{
      "scriptId":"u49"},
    "eee6769e07284298b1f7f658b86ef5b4":{
      "scriptId":"u50"},
    "c5bb7a98d3254316a69d3dd301357c82":{
      "scriptId":"u51"},
    "e83f46de35bc4170a5b7918261f9e49d":{
      "scriptId":"u52"},
    "32be16f225bc498a80a24c7dc05231e5":{
      "scriptId":"u53"},
    "c79617a78e4f4a939d59d2f4e57e5a15":{
      "scriptId":"u54"},
    "c1febaa876a84671a4cdba3c6df7ff91":{
      "scriptId":"u55"},
    "a93c8ccbf06944efb7b3cd31d67169f3":{
      "scriptId":"u56"},
    "e9a75c0a758548dbb3cc244525444a88":{
      "scriptId":"u57"},
    "c711b641707f4eb2a8eebd639358a716":{
      "scriptId":"u58"},
    "76e2c32170fc4ce5958ecb078c902fdd":{
      "scriptId":"u59"},
    "e6dc5a69e3614e6dabe8dc2ebf154bbe":{
      "scriptId":"u60"},
    "f5fbbd9f1a204eab955aabb2c72aa5e5":{
      "scriptId":"u61"}}});