$axure.loadCurrentPage({
  "url":"创建拉钩.html",
  "generationDate":new Date(1393298916453.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"59d4cc95455f48e98f16bcac7f7de58e",
    "type":"Axure:Page",
    "name":"创建拉钩",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9dbc1792046d4abe9bdd239a9bc59cf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":0},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2167c934356a43b386efc80f6e2636c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":0},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u2.png"}},
{
          "id":"174065e3b7f9402fad3a45a036115773",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":1},
            "size":{
              "width":319,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12fed0c1391b4b1db8f64632a32fecf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":1},
                "size":{
                  "width":319,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u4.png"}},
{
          "id":"b6d8e2eae98d4f84b30d570efb7b222f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":3,
              "y":20},
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4676b1bb6a342e09c9ca5299bea6dcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":3,
                  "y":20},
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u106.png"}},
{
          "id":"f40916f11ad643469bcb5349b3fcae3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":34},
            "size":{
              "width":37,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bac2c03b7b9421f9fb880bfbe031150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":34},
                "size":{
                  "width":37,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c35f338f4572426da050a2f8adf91d96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af571bc7a7324d699c67b120226ef1ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u249.png"}},
{
          "id":"a73dd6cee39a4664a8c198fdd1934912",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":36},
            "size":{
              "width":36,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d925ca2a8a845b3b2e4b89e32581236",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":36},
                "size":{
                  "width":36,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30ea7fd5a498411eb8d8c91739fb02c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":74},
            "size":{
              "width":299,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b722d19e56cc446c87c34a29c7f8fd69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":74},
                "size":{
                  "width":299,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建拉钩/u12.png"}},
{
          "id":"79f2425c57e745cbaee341e8fc33c7c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":112},
            "size":{
              "width":299,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f0986ac8cb04b8282439695a29beb38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":112},
                "size":{
                  "width":299,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建拉钩/u14.png"}},
{
          "id":"9b26054d3d0248f5ab15d7befcf9a175",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":23,
              "y":85},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d3f9df3df4b40249844ba989bc75ff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":85},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d81cd954466c4916801eb924c0b632ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":23,
              "y":122},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18b6479202cf4f508406ef6b6d15b820",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":122},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9e62cb8956a42388b978d9403054abd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":217},
            "size":{
              "width":299,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b840168ee4c450e8d68d71f32ed627d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":217},
                "size":{
                  "width":299,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建拉钩/u20.png"}},
{
          "id":"06476431ee254671b138801631c18482",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":266},
            "size":{
              "width":128,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"584aa1dca8704644a74039ec5ed8dad0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":266},
                "size":{
                  "width":128,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]},
{
                      "action":"fadeWidget",
                      "description":"显示 循环类型 向上滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["9b642a86d8e445948caaab14eb96ce15"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/创建拉钩/u22.png"}},
{
          "id":"e168b81d888b41109af79f3a61d0d34d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":266},
            "size":{
              "width":171,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf8dfbc5ab2a4d2688c02196a2678d51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":266},
                "size":{
                  "width":171,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建拉钩/u24.png"}},
{
          "id":"fe850778b2364545966ea9d9941019df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":324},
            "size":{
              "width":299,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2f0ea0c4f884d628964d920debb7dea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":324},
                "size":{
                  "width":299,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建拉钩/u26.png"}},
{
          "id":"d119ab39cb8e45158a3d91073ebaa9b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":336},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69c17cdbdfb341eb94e5237702224e76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":336},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b751d85fef8745a4829576c98edbe73e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":212,
              "y":331},
            "size":{
              "width":94,
              "height":27},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1f6ada3d7ed4033a338fcddd7a9b3c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":212,
                  "y":331},
                "size":{
                  "width":94,
                  "height":27},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建拉钩/u30.png"}},
{
          "id":"e8f38117aef247ce9140ad31edb24a4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":95,
              "y":375},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df1674d0caac442d93d40073f4d75d69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":95,
                  "y":375},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f7ba00e24314f749c7e731c684fbf27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":3,
              "y":20},
            "size":{
              "width":54,
              "height":43},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b65d5c781eb548a9a942153ee614f6a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":3,
                  "y":20},
                "size":{
                  "width":54,
                  "height":43},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 家庭首页",
                      "target":{
                        "targetType":"page",
                        "url":"家庭首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b7ffcbc30244a3fa59ac3e563b15fa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":23,
              "y":234},
            "size":{
              "width":118,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78aeb310472f44c392405215ecf6bf4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":234},
                "size":{
                  "width":118,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ddc3cf4c8a7421f86d7ae2de93b8df4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "location":{
              "x":339,
              "y":14},
            "size":{
              "width":150,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d86128f1ae748c3a9cbbc5245ff3f37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "location":{
                  "x":339,
                  "y":14},
                "size":{
                  "width":150,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"72faee834cb3405d9cedc32cb5a5a676",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":348,
              "y":48},
            "size":{
              "width":308,
              "height":48},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a99ad49fd669431c8b5ea962694b1012",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":348,
                  "y":48},
                "size":{
                  "width":308,
                  "height":48},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b642a86d8e445948caaab14eb96ce15",
          "label":"循环类型",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":3,
              "y":0},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"72f15a3b428e4023b25ea46bad8ef488",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2a81984c0d2047a9a2a20291a111d65f",
                  "label":"",
                  "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0x3A000000},
                    "size":{
                      "width":320,
                      "height":480},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d3c791107f634ba1bba56492ae445b21",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0x3A000000},
                        "size":{
                          "width":320,
                          "height":480},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建拉钩/u43.png"}},
{
                  "id":"f0f16fb5d84349f5a39bfa83501fbfa4",
                  "label":"",
                  "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'黑体 Bold', '黑体'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F9CF1,
                      "opacity":1},
                    "location":{
                      "x":7,
                      "y":426},
                    "size":{
                      "width":304,
                      "height":45},
                    "borderWidth":"-1",
                    "cornerRadiusTopLeft":"6"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"54f75833866744699776173c92936fe1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'黑体 Bold', '黑体'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F9CF1,
                          "opacity":1},
                        "location":{
                          "x":7,
                          "y":426},
                        "size":{
                          "width":304,
                          "height":45},
                        "borderWidth":"-1",
                        "cornerRadiusTopLeft":"6"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 循环类型 向下滑动 500 ms",
                              "objectsToFades":[{
                                  "objectPath":["9b642a86d8e445948caaab14eb96ce15"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"slideDown",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/创建拉钩/u45.png"}},
{
                  "id":"08a75d0028ab4245bb3257a993e13cb0",
                  "label":"",
                  "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'黑体 Bold', '黑体'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F9CF1,
                      "opacity":1},
                    "location":{
                      "x":7,
                      "y":371},
                    "size":{
                      "width":304,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"6"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"82f205e7a32649e8adc6b970b169323b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'黑体 Bold', '黑体'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F9CF1,
                          "opacity":1},
                        "location":{
                          "x":7,
                          "y":371},
                        "size":{
                          "width":304,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"6"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建拉钩/u47.png"}},
{
                  "id":"2addfe5d43024a47981f3c157aad2ae6",
                  "label":"",
                  "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'黑体 Bold', '黑体'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F9CF1,
                      "opacity":1},
                    "location":{
                      "x":7,
                      "y":325},
                    "size":{
                      "width":304,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cba16a39e1c54b6b894c47ae4865ad0b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'黑体 Bold', '黑体'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F9CF1,
                          "opacity":1},
                        "location":{
                          "x":7,
                          "y":325},
                        "size":{
                          "width":304,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建拉钩/u49.png"}},
{
                  "id":"bb1db7f93c9a43d886eea2d25efe618b",
                  "label":"",
                  "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'黑体 Bold', '黑体'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F9CF1,
                      "opacity":1},
                    "location":{
                      "x":7,
                      "y":280},
                    "size":{
                      "width":304,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25f75b63322c45eca02bf407553fea9a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'黑体 Bold', '黑体'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F9CF1,
                          "opacity":1},
                        "location":{
                          "x":7,
                          "y":280},
                        "size":{
                          "width":304,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建拉钩/u49.png"}},
{
                  "id":"97e45fce88d64889b823dda48c78c696",
                  "label":"",
                  "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'黑体 Bold', '黑体'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F9CF1,
                      "opacity":1},
                    "location":{
                      "x":7,
                      "y":235},
                    "size":{
                      "width":304,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ebf4664d10f04d48990457b39bf086c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'黑体 Bold', '黑体'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F9CF1,
                          "opacity":1},
                        "location":{
                          "x":7,
                          "y":235},
                        "size":{
                          "width":304,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建拉钩/u49.png"}},
{
                  "id":"1635f4590e9a4ec486cb3e7fc27f2670",
                  "label":"",
                  "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'黑体 Regular', '黑体'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":7,
                      "y":144},
                    "size":{
                      "width":304,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"6"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66645da8c2a64d948c655d6e31877c84",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'黑体 Regular', '黑体'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":7,
                          "y":144},
                        "size":{
                          "width":304,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"6"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建拉钩/u55.png"}},
{
                  "id":"41478d78662441488616c6bd69e67f6f",
                  "label":"",
                  "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'黑体 Bold', '黑体'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF4F9CF1,
                      "opacity":1},
                    "location":{
                      "x":7,
                      "y":190},
                    "size":{
                      "width":304,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a2954d239acf4ccf9d80bab3339ce779",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9b642a86d8e445948caaab14eb96ce15",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'黑体 Bold', '黑体'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF4F9CF1,
                          "opacity":1},
                        "location":{
                          "x":7,
                          "y":190},
                        "size":{
                          "width":304,
                          "height":45},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建拉钩/u49.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"7bd835a243284b3cb41298f643af182d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1668,
              "y":365},
            "size":{
              "width":320,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a931aca8377c4567b6b4c43fcea847d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1668,
                  "y":365},
                "size":{
                  "width":320,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建拉钩/u59.png"}},
{
          "id":"67cef712e00b41279c0cec4b7517d503",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1668,
              "y":339},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9660c4c7c0b464dbf67cc0627a98b35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1668,
                  "y":339},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "9dbc1792046d4abe9bdd239a9bc59cf0":{
      "scriptId":"u0"},
    "2167c934356a43b386efc80f6e2636c1":{
      "scriptId":"u1"},
    "174065e3b7f9402fad3a45a036115773":{
      "scriptId":"u2"},
    "12fed0c1391b4b1db8f64632a32fecf3":{
      "scriptId":"u3"},
    "b6d8e2eae98d4f84b30d570efb7b222f":{
      "scriptId":"u4"},
    "b4676b1bb6a342e09c9ca5299bea6dcb":{
      "scriptId":"u5"},
    "f40916f11ad643469bcb5349b3fcae3b":{
      "scriptId":"u6"},
    "8bac2c03b7b9421f9fb880bfbe031150":{
      "scriptId":"u7"},
    "c35f338f4572426da050a2f8adf91d96":{
      "scriptId":"u8"},
    "af571bc7a7324d699c67b120226ef1ae":{
      "scriptId":"u9"},
    "a73dd6cee39a4664a8c198fdd1934912":{
      "scriptId":"u10"},
    "2d925ca2a8a845b3b2e4b89e32581236":{
      "scriptId":"u11"},
    "30ea7fd5a498411eb8d8c91739fb02c9":{
      "scriptId":"u12"},
    "b722d19e56cc446c87c34a29c7f8fd69":{
      "scriptId":"u13"},
    "79f2425c57e745cbaee341e8fc33c7c8":{
      "scriptId":"u14"},
    "2f0986ac8cb04b8282439695a29beb38":{
      "scriptId":"u15"},
    "9b26054d3d0248f5ab15d7befcf9a175":{
      "scriptId":"u16"},
    "4d3f9df3df4b40249844ba989bc75ff4":{
      "scriptId":"u17"},
    "d81cd954466c4916801eb924c0b632ea":{
      "scriptId":"u18"},
    "18b6479202cf4f508406ef6b6d15b820":{
      "scriptId":"u19"},
    "e9e62cb8956a42388b978d9403054abd":{
      "scriptId":"u20"},
    "0b840168ee4c450e8d68d71f32ed627d":{
      "scriptId":"u21"},
    "06476431ee254671b138801631c18482":{
      "scriptId":"u22"},
    "584aa1dca8704644a74039ec5ed8dad0":{
      "scriptId":"u23"},
    "e168b81d888b41109af79f3a61d0d34d":{
      "scriptId":"u24"},
    "cf8dfbc5ab2a4d2688c02196a2678d51":{
      "scriptId":"u25"},
    "fe850778b2364545966ea9d9941019df":{
      "scriptId":"u26"},
    "d2f0ea0c4f884d628964d920debb7dea":{
      "scriptId":"u27"},
    "d119ab39cb8e45158a3d91073ebaa9b7":{
      "scriptId":"u28"},
    "69c17cdbdfb341eb94e5237702224e76":{
      "scriptId":"u29"},
    "b751d85fef8745a4829576c98edbe73e":{
      "scriptId":"u30"},
    "a1f6ada3d7ed4033a338fcddd7a9b3c4":{
      "scriptId":"u31"},
    "e8f38117aef247ce9140ad31edb24a4e":{
      "scriptId":"u32"},
    "df1674d0caac442d93d40073f4d75d69":{
      "scriptId":"u33"},
    "2f7ba00e24314f749c7e731c684fbf27":{
      "scriptId":"u34"},
    "b65d5c781eb548a9a942153ee614f6a6":{
      "scriptId":"u35"},
    "2b7ffcbc30244a3fa59ac3e563b15fa6":{
      "scriptId":"u36"},
    "78aeb310472f44c392405215ecf6bf4e":{
      "scriptId":"u37"},
    "6ddc3cf4c8a7421f86d7ae2de93b8df4":{
      "scriptId":"u38"},
    "7d86128f1ae748c3a9cbbc5245ff3f37":{
      "scriptId":"u39"},
    "72faee834cb3405d9cedc32cb5a5a676":{
      "scriptId":"u40"},
    "a99ad49fd669431c8b5ea962694b1012":{
      "scriptId":"u41"},
    "9b642a86d8e445948caaab14eb96ce15":{
      "scriptId":"u42"},
    "2a81984c0d2047a9a2a20291a111d65f":{
      "scriptId":"u43"},
    "d3c791107f634ba1bba56492ae445b21":{
      "scriptId":"u44"},
    "f0f16fb5d84349f5a39bfa83501fbfa4":{
      "scriptId":"u45"},
    "54f75833866744699776173c92936fe1":{
      "scriptId":"u46"},
    "08a75d0028ab4245bb3257a993e13cb0":{
      "scriptId":"u47"},
    "82f205e7a32649e8adc6b970b169323b":{
      "scriptId":"u48"},
    "2addfe5d43024a47981f3c157aad2ae6":{
      "scriptId":"u49"},
    "cba16a39e1c54b6b894c47ae4865ad0b":{
      "scriptId":"u50"},
    "bb1db7f93c9a43d886eea2d25efe618b":{
      "scriptId":"u51"},
    "25f75b63322c45eca02bf407553fea9a":{
      "scriptId":"u52"},
    "97e45fce88d64889b823dda48c78c696":{
      "scriptId":"u53"},
    "ebf4664d10f04d48990457b39bf086c2":{
      "scriptId":"u54"},
    "1635f4590e9a4ec486cb3e7fc27f2670":{
      "scriptId":"u55"},
    "66645da8c2a64d948c655d6e31877c84":{
      "scriptId":"u56"},
    "41478d78662441488616c6bd69e67f6f":{
      "scriptId":"u57"},
    "a2954d239acf4ccf9d80bab3339ce779":{
      "scriptId":"u58"},
    "7bd835a243284b3cb41298f643af182d":{
      "scriptId":"u59"},
    "a931aca8377c4567b6b4c43fcea847d7":{
      "scriptId":"u60"},
    "67cef712e00b41279c0cec4b7517d503":{
      "scriptId":"u61"},
    "d9660c4c7c0b464dbf67cc0627a98b35":{
      "scriptId":"u62"}}});