$axure.loadCurrentPage({
  "url":"编辑家庭资料.html",
  "generationDate":new Date(1393298916282.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7cc2f1c0539a4820910d07ed9adb76b7",
    "type":"Axure:Page",
    "name":"编辑家庭资料",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a06a3c9e10ee41b18f4ded5d8324fe4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":0},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e55b772b349442cb87d6fe89305ab4c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":0},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u2.png"}},
{
          "id":"bac4ae63988d46578f46becb5d89e1d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":1},
            "size":{
              "width":319,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23c6feed1bcd4893a9c0011fc5cf2340",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":1},
                "size":{
                  "width":319,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u4.png"}},
{
          "id":"c6b1744a81f34723b075a805053281e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":3,
              "y":20},
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d94fce0914645429db92908b5b56d5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":3,
                  "y":20},
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u106.png"}},
{
          "id":"e11fa5bd7ad3454da6673ad8d693a37d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":34},
            "size":{
              "width":37,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ac348454682450ca6754941da5f417a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":34},
                "size":{
                  "width":37,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4c426e73a8943f7a99a505a31fd29a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":76},
            "size":{
              "width":300,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a109adcdb54b422980e84b0cc01b2eb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":76},
                "size":{
                  "width":300,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑家庭资料/u8.png"}},
{
          "id":"876529c62f9843abac623ca62103b327",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":3,
              "y":20},
            "size":{
              "width":54,
              "height":43},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"528686c3f3d84cf6becebc5718f77110",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":3,
                  "y":20},
                "size":{
                  "width":54,
                  "height":43},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec9fec2be549408187601d58ff1695fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":21,
              "y":90},
            "size":{
              "width":72,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b28c35350ace402fabc1e7c794b51abb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":21,
                  "y":90},
                "size":{
                  "width":72,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3aab1fc4481f43e990e40e8e8d4f0ef4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":85},
            "size":{
              "width":24,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ea0ea96be2f4e098c8a400f9feb1257",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":85},
                "size":{
                  "width":24,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u42.png"}},
{
          "id":"b959656374b744448630e76beaaaf42d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":90},
            "size":{
              "width":72,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1872684aba1f4dabb52bd03f6b447c4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":90},
                "size":{
                  "width":72,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5f37ff889be4dfdb73f101c59aa26f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":120},
            "size":{
              "width":300,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cf66fc163a4438f966423db72b20f5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":120},
                "size":{
                  "width":300,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑家庭资料/u8.png"}},
{
          "id":"fdf45a05e27a4ef88769310fe6f18300",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":237,
              "y":134},
            "size":{
              "width":73,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcaa3eda82e146f98fd81abf47dbb490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":237,
                  "y":134},
                "size":{
                  "width":73,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5620a2d307449e9bf80b19ce4561fd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":23,
              "y":134},
            "size":{
              "width":72,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9424b03582cb46aab8bfe99f36735405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":23,
                  "y":134},
                "size":{
                  "width":72,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a721259c8960457085a9667959634c1f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":129},
            "size":{
              "width":24,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3e369866974427daf22823528f49edb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":129},
                "size":{
                  "width":24,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u42.png"}},
{
          "id":"828134a6b894409e9110974d4a48c158",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":188},
            "size":{
              "width":300,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19644865a5c043efb37778ac807d7900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":188},
                "size":{
                  "width":300,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑家庭资料/u26.png"}},
{
          "id":"51536d10a08e4ceb80b18a4285fba056",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":23,
              "y":202},
            "size":{
              "width":72,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f564e3d355944553b8d881b0422658e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":23,
                  "y":202},
                "size":{
                  "width":72,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a94bd658f8b49e1bc7723f400705b42",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":212},
            "size":{
              "width":24,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"899b7487a9ae47c2bcc2e86cef56a6b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":212},
                "size":{
                  "width":24,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/导航/u42.png"}},
{
          "id":"f51e2bf9c5054f3b843f9cd3b19e5bfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":228},
            "size":{
              "width":284,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"380376ed6c1040a2a02b6f962a1ebcad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":228},
                "size":{
                  "width":284,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56097460fe03494ab3e7cc1eb972c4e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":26},
            "size":{
              "width":339,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e89e477759d487ab3f1dc9c6b53832d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":341,
                  "y":26},
                "size":{
                  "width":339,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c07b684746b1477e83cb653b3fa392ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":34},
            "size":{
              "width":35,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71e0cc2453d04569a39f53301a11824b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":34},
                "size":{
                  "width":35,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a06a3c9e10ee41b18f4ded5d8324fe4c":{
      "scriptId":"u0"},
    "e55b772b349442cb87d6fe89305ab4c1":{
      "scriptId":"u1"},
    "bac4ae63988d46578f46becb5d89e1d2":{
      "scriptId":"u2"},
    "23c6feed1bcd4893a9c0011fc5cf2340":{
      "scriptId":"u3"},
    "c6b1744a81f34723b075a805053281e0":{
      "scriptId":"u4"},
    "4d94fce0914645429db92908b5b56d5e":{
      "scriptId":"u5"},
    "e11fa5bd7ad3454da6673ad8d693a37d":{
      "scriptId":"u6"},
    "3ac348454682450ca6754941da5f417a":{
      "scriptId":"u7"},
    "d4c426e73a8943f7a99a505a31fd29a0":{
      "scriptId":"u8"},
    "a109adcdb54b422980e84b0cc01b2eb4":{
      "scriptId":"u9"},
    "876529c62f9843abac623ca62103b327":{
      "scriptId":"u10"},
    "528686c3f3d84cf6becebc5718f77110":{
      "scriptId":"u11"},
    "ec9fec2be549408187601d58ff1695fa":{
      "scriptId":"u12"},
    "b28c35350ace402fabc1e7c794b51abb":{
      "scriptId":"u13"},
    "3aab1fc4481f43e990e40e8e8d4f0ef4":{
      "scriptId":"u14"},
    "5ea0ea96be2f4e098c8a400f9feb1257":{
      "scriptId":"u15"},
    "b959656374b744448630e76beaaaf42d":{
      "scriptId":"u16"},
    "1872684aba1f4dabb52bd03f6b447c4a":{
      "scriptId":"u17"},
    "b5f37ff889be4dfdb73f101c59aa26f8":{
      "scriptId":"u18"},
    "8cf66fc163a4438f966423db72b20f5e":{
      "scriptId":"u19"},
    "fdf45a05e27a4ef88769310fe6f18300":{
      "scriptId":"u20"},
    "dcaa3eda82e146f98fd81abf47dbb490":{
      "scriptId":"u21"},
    "e5620a2d307449e9bf80b19ce4561fd4":{
      "scriptId":"u22"},
    "9424b03582cb46aab8bfe99f36735405":{
      "scriptId":"u23"},
    "a721259c8960457085a9667959634c1f":{
      "scriptId":"u24"},
    "f3e369866974427daf22823528f49edb":{
      "scriptId":"u25"},
    "828134a6b894409e9110974d4a48c158":{
      "scriptId":"u26"},
    "19644865a5c043efb37778ac807d7900":{
      "scriptId":"u27"},
    "51536d10a08e4ceb80b18a4285fba056":{
      "scriptId":"u28"},
    "f564e3d355944553b8d881b0422658e3":{
      "scriptId":"u29"},
    "1a94bd658f8b49e1bc7723f400705b42":{
      "scriptId":"u30"},
    "899b7487a9ae47c2bcc2e86cef56a6b3":{
      "scriptId":"u31"},
    "f51e2bf9c5054f3b843f9cd3b19e5bfb":{
      "scriptId":"u32"},
    "380376ed6c1040a2a02b6f962a1ebcad":{
      "scriptId":"u33"},
    "56097460fe03494ab3e7cc1eb972c4e7":{
      "scriptId":"u34"},
    "3e89e477759d487ab3f1dc9c6b53832d":{
      "scriptId":"u35"},
    "c07b684746b1477e83cb653b3fa392ba":{
      "scriptId":"u36"},
    "71e0cc2453d04569a39f53301a11824b":{
      "scriptId":"u37"}}});