$axure.loadCurrentPage({
  "url":"编辑.html",
  "generationDate":new Date(1392634062192.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ec672c0d99574db88395172a87d36b15",
    "type":"Axure:Page",
    "name":"编辑",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6148439daf0e4501ac0b6f0352f4d59a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":0},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f3a8bd043184881a7e7909152491c91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":0},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"ed44c79ad2484bc08248d6dbb5a923c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":1},
            "size":{
              "width":319,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64a265dce95b4043a221d2cca8470f29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":1},
                "size":{
                  "width":319,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"090268f520b64468a6fae06027ff7d2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":3,
              "y":20},
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4efb344c8181473c9c4035005955cac9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":3,
                  "y":20},
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u106.png"}},
{
          "id":"5271d88ad58e45919912962487d79a9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":34},
            "size":{
              "width":37,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28b136f2fcee49f8843ca21c16c489fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":34},
                "size":{
                  "width":37,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"457ebaed576349e6a932e22601a24895",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04325d67a3f14549ba358cbc996f95b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u245.png"}},
{
          "id":"94f29fcc7e274b2bb766b60b9e71c4bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":76},
            "size":{
              "width":300,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a357c95bb0d4cb3b8168cc19cc80a1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":76},
                "size":{
                  "width":300,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑/u10.png"}},
{
          "id":"265d9151f5bf4900a3f7eb1db86c2867",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":3,
              "y":20},
            "size":{
              "width":54,
              "height":43},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cc42ea610064e73be32b10623613743",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":3,
                  "y":20},
                "size":{
                  "width":54,
                  "height":43},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25a916b37b674cb6b6e26b02acec33fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":21,
              "y":90},
            "size":{
              "width":72,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8028f54a53044aef900e24e2798939e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":21,
                  "y":90},
                "size":{
                  "width":72,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e420f73dfdd4550be41284af4e482fa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":85},
            "size":{
              "width":24,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f4dd09a02004658bd88a2d84fa5f29d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":85},
                "size":{
                  "width":24,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"695664b3e0d84400bb51d90937c1be8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":90},
            "size":{
              "width":72,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d274e1e143e44b17a12b9abd8a00749c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":90},
                "size":{
                  "width":72,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8348c8ae102c4ee1ba3dc619c6d4da21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":120},
            "size":{
              "width":300,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8537dce2c282441cbdd03dcdefe49e37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":120},
                "size":{
                  "width":300,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑/u10.png"}},
{
          "id":"e9b2cb602d95481eb44fdc93f1d7c57c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":237,
              "y":134},
            "size":{
              "width":73,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"773718338cab4c0e91e61890db5ba049",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":237,
                  "y":134},
                "size":{
                  "width":73,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ffc256d42f34b679ed6810c165ffbdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":23,
              "y":134},
            "size":{
              "width":72,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a31328e92ea94375a51969253dab9ad5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":23,
                  "y":134},
                "size":{
                  "width":72,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"396650f8ee74443284f1a626d7ed857a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":129},
            "size":{
              "width":24,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b1f97a6b3da47fdb0100080ab770743",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":129},
                "size":{
                  "width":24,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"347f908331b142208ec83b4875cb8729",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":188},
            "size":{
              "width":300,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"562bda41409045558afb04cb6cd68809",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":188},
                "size":{
                  "width":300,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑/u28.png"}},
{
          "id":"bd295b6fbd7d47e3a15b2a5cc66958d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":23,
              "y":202},
            "size":{
              "width":72,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a7b60b8112b48d99c596b1c2b165382",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":23,
                  "y":202},
                "size":{
                  "width":72,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd29c6c1a6f24827bb6736dcde02e6ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":212},
            "size":{
              "width":24,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"489060b4454a4e3b84d341cbd61babba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":212},
                "size":{
                  "width":24,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"c5c15da8582040228a0acafd1ef078a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":228},
            "size":{
              "width":284,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c6d569e39fe4cfe8e1fb87e12daf614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":228},
                "size":{
                  "width":284,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e190ca2db92b44beb4c30e2c77d3af15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":26},
            "size":{
              "width":339,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbf099671b08453abef3ee7674a38d0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":341,
                  "y":26},
                "size":{
                  "width":339,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93d39f57b44742089c05a1957ac8af8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":282,
              "y":34},
            "size":{
              "width":35,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26ded180b2c34ea1b4543f15cc4cfa2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":282,
                  "y":34},
                "size":{
                  "width":35,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6148439daf0e4501ac0b6f0352f4d59a":{
      "scriptId":"u0"},
    "1f3a8bd043184881a7e7909152491c91":{
      "scriptId":"u1"},
    "ed44c79ad2484bc08248d6dbb5a923c6":{
      "scriptId":"u2"},
    "64a265dce95b4043a221d2cca8470f29":{
      "scriptId":"u3"},
    "090268f520b64468a6fae06027ff7d2f":{
      "scriptId":"u4"},
    "4efb344c8181473c9c4035005955cac9":{
      "scriptId":"u5"},
    "5271d88ad58e45919912962487d79a9d":{
      "scriptId":"u6"},
    "28b136f2fcee49f8843ca21c16c489fe":{
      "scriptId":"u7"},
    "457ebaed576349e6a932e22601a24895":{
      "scriptId":"u8"},
    "04325d67a3f14549ba358cbc996f95b6":{
      "scriptId":"u9"},
    "94f29fcc7e274b2bb766b60b9e71c4bb":{
      "scriptId":"u10"},
    "2a357c95bb0d4cb3b8168cc19cc80a1f":{
      "scriptId":"u11"},
    "265d9151f5bf4900a3f7eb1db86c2867":{
      "scriptId":"u12"},
    "3cc42ea610064e73be32b10623613743":{
      "scriptId":"u13"},
    "25a916b37b674cb6b6e26b02acec33fd":{
      "scriptId":"u14"},
    "8028f54a53044aef900e24e2798939e7":{
      "scriptId":"u15"},
    "4e420f73dfdd4550be41284af4e482fa":{
      "scriptId":"u16"},
    "5f4dd09a02004658bd88a2d84fa5f29d":{
      "scriptId":"u17"},
    "695664b3e0d84400bb51d90937c1be8d":{
      "scriptId":"u18"},
    "d274e1e143e44b17a12b9abd8a00749c":{
      "scriptId":"u19"},
    "8348c8ae102c4ee1ba3dc619c6d4da21":{
      "scriptId":"u20"},
    "8537dce2c282441cbdd03dcdefe49e37":{
      "scriptId":"u21"},
    "e9b2cb602d95481eb44fdc93f1d7c57c":{
      "scriptId":"u22"},
    "773718338cab4c0e91e61890db5ba049":{
      "scriptId":"u23"},
    "8ffc256d42f34b679ed6810c165ffbdd":{
      "scriptId":"u24"},
    "a31328e92ea94375a51969253dab9ad5":{
      "scriptId":"u25"},
    "396650f8ee74443284f1a626d7ed857a":{
      "scriptId":"u26"},
    "1b1f97a6b3da47fdb0100080ab770743":{
      "scriptId":"u27"},
    "347f908331b142208ec83b4875cb8729":{
      "scriptId":"u28"},
    "562bda41409045558afb04cb6cd68809":{
      "scriptId":"u29"},
    "bd295b6fbd7d47e3a15b2a5cc66958d8":{
      "scriptId":"u30"},
    "7a7b60b8112b48d99c596b1c2b165382":{
      "scriptId":"u31"},
    "cd29c6c1a6f24827bb6736dcde02e6ef":{
      "scriptId":"u32"},
    "489060b4454a4e3b84d341cbd61babba":{
      "scriptId":"u33"},
    "c5c15da8582040228a0acafd1ef078a4":{
      "scriptId":"u34"},
    "1c6d569e39fe4cfe8e1fb87e12daf614":{
      "scriptId":"u35"},
    "e190ca2db92b44beb4c30e2c77d3af15":{
      "scriptId":"u36"},
    "fbf099671b08453abef3ee7674a38d0e":{
      "scriptId":"u37"},
    "93d39f57b44742089c05a1957ac8af8a":{
      "scriptId":"u38"},
    "26ded180b2c34ea1b4543f15cc4cfa2d":{
      "scriptId":"u39"}}});