$axure.loadCurrentPage({
  "url":"更换皮肤.html",
  "generationDate":new Date(1392634061549.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5bc8808b19cc4b3ea5e41821d6c9a4da",
    "type":"Axure:Page",
    "name":"更换皮肤",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f5b1649ffa8e4e6cb43830ac31088949",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ae6c7ab622f4d10b6f8677472471d2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"856b9fd391024a2d98e759fbbb90abcc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":1},
            "size":{
              "width":319,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f87f6ff5eddf4089abe0a0081a4acca2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":1},
                "size":{
                  "width":319,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"9b74b418f896400a8360a77ebba2aa21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70c3b6a803d54b0d9f49b2f3597d0e19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u106.png"}},
{
          "id":"823e57666b1e4ad0b6be6b598ec85ee7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":34},
            "size":{
              "width":37,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2030c023edb44c178371b3792053c664",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":34},
                "size":{
                  "width":37,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbda7572fee2454a812728b4bfdfc7a9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abf3f148b81f4206b1854f5496ed0d0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u245.png"}},
{
          "id":"193afac550884d93a417e36007e135a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "location":{
              "x":336,
              "y":20},
            "size":{
              "width":150,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b33250d6c98546b2af7de4dffc1f4794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "location":{
                  "x":336,
                  "y":20},
                "size":{
                  "width":150,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5150e5ccf0b94601a017b1ea54c68359",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":59},
            "size":{
              "width":223,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7f8ae26b75741b88cfbce49a26edd13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":59},
                "size":{
                  "width":223,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57f9466e14974908ad9de4a4a5869188",
          "label":"皮肤2",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":200},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"fe0ff6af01d74361ba6606df0e620b42",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b28e07349b1b4522b03a04477f079032",
                  "label":"",
                  "parentDynamicPanel":"57f9466e14974908ad9de4a4a5869188",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":302,
                      "height":106},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6a4ebaba0ba4b4298b5dba38a5f6513",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57f9466e14974908ad9de4a4a5869188",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":302,
                          "height":106},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 皮肤2 to 状态2,<br>皮肤1 to 状态1,<br>皮肤3 to 状态1",
                              "panelsToStates":[{
                                  "panelPath":["57f9466e14974908ad9de4a4a5869188"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}},
{
                                  "panelPath":["5e8180be326045ecae6d23928df404eb"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}},
{
                                  "panelPath":["e22b28cb8a1b415f995045c85668da13"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/更换皮肤/u15.png"}},
{
                  "id":"2a8e872ef094480c8d53c9bdbaefb7f2",
                  "label":"",
                  "parentDynamicPanel":"57f9466e14974908ad9de4a4a5869188",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":84},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3de57eac579244fca7b8e178b8aa1be3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57f9466e14974908ad9de4a4a5869188",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":84},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"b1b2a0497b00456784ec3c2bdea2cdec",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3c4eaf3670cc4b2b8a38b257506bdb57",
                  "label":"",
                  "parentDynamicPanel":"57f9466e14974908ad9de4a4a5869188",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":302,
                      "height":106},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eef5e33687364bfd866bd31b864c53d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57f9466e14974908ad9de4a4a5869188",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":302,
                          "height":106},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/更换皮肤/u19.png"}},
{
                  "id":"0cbd156558a04bc7a217a542b2b0cf83",
                  "label":"",
                  "parentDynamicPanel":"57f9466e14974908ad9de4a4a5869188",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":273,
                      "y":77},
                    "size":{
                      "width":25,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4dd409cc51f4e8390d2dc9ead34d275",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57f9466e14974908ad9de4a4a5869188",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":273,
                          "y":77},
                        "size":{
                          "width":25,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u35.png"}},
{
                  "id":"2799cccd45e94c23b6a0423bcc5aa56d",
                  "label":"",
                  "parentDynamicPanel":"57f9466e14974908ad9de4a4a5869188",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":82},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25441e26b3fd4a61befa475297a0703a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57f9466e14974908ad9de4a4a5869188",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":82},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"2e11b440817d4582b9e1d974891f3e70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":94},
            "size":{
              "width":261,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4906a0325d774475b493d30340f7cf75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":94},
                "size":{
                  "width":261,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e8180be326045ecae6d23928df404eb",
          "label":"皮肤1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":78},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d63c198f36d14235931d52ae2263c5be",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0bbba94c868f4ea596546b2cec0bdef4",
                  "label":"",
                  "parentDynamicPanel":"5e8180be326045ecae6d23928df404eb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":302,
                      "height":106},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"65f8d43a43f14e279a43bd6aff63e1a6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5e8180be326045ecae6d23928df404eb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":302,
                          "height":106},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/更换皮肤/u19.png"}},
{
                  "id":"50a409a927ba44118193d332ac60eb2c",
                  "label":"",
                  "parentDynamicPanel":"5e8180be326045ecae6d23928df404eb",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":273,
                      "y":77},
                    "size":{
                      "width":25,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"244d0c3bf3a34cbaafe99bdf1efd23f6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5e8180be326045ecae6d23928df404eb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":273,
                          "y":77},
                        "size":{
                          "width":25,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u35.png"}},
{
                  "id":"e538b82b16ca47af8cff283ca85dbdf5",
                  "label":"",
                  "parentDynamicPanel":"5e8180be326045ecae6d23928df404eb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":82},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8be4430138a24d87a149d79f1a325dc6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5e8180be326045ecae6d23928df404eb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":82},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"eb4a7e38741140448af3910f5b834683",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"aacd5c8e3f9a4814a0f4a7c178406218",
                  "label":"",
                  "parentDynamicPanel":"5e8180be326045ecae6d23928df404eb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":302,
                      "height":106},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c15e97e2ba514e79ac548832bba60d28",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5e8180be326045ecae6d23928df404eb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":302,
                          "height":106},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 皮肤2 to 状态1,<br>皮肤1 to 状态2,<br>皮肤3 to 状态1",
                              "panelsToStates":[{
                                  "panelPath":["57f9466e14974908ad9de4a4a5869188"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}},
{
                                  "panelPath":["5e8180be326045ecae6d23928df404eb"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}},
{
                                  "panelPath":["e22b28cb8a1b415f995045c85668da13"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/更换皮肤/u15.png"}},
{
                  "id":"ffa47afd980a43eaa0b2a884c8684f2d",
                  "label":"",
                  "parentDynamicPanel":"5e8180be326045ecae6d23928df404eb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":84},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe5f056bab504b4197641f55911fbea2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5e8180be326045ecae6d23928df404eb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":84},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"e22b28cb8a1b415f995045c85668da13",
          "label":"皮肤3",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":9,
              "y":322},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"2703e9875d0f4bd48dc981d9168012eb",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"532df366b2de46f48ad7fcebf864483f",
                  "label":"",
                  "parentDynamicPanel":"e22b28cb8a1b415f995045c85668da13",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":302,
                      "height":106},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4dc5f5704b6b4e149828624778e1dae5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e22b28cb8a1b415f995045c85668da13",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":302,
                          "height":106},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 皮肤2 to 状态1,<br>皮肤1 to 状态1,<br>皮肤3 to 状态2",
                              "panelsToStates":[{
                                  "panelPath":["57f9466e14974908ad9de4a4a5869188"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}},
{
                                  "panelPath":["5e8180be326045ecae6d23928df404eb"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}},
{
                                  "panelPath":["e22b28cb8a1b415f995045c85668da13"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/更换皮肤/u15.png"}},
{
                  "id":"d3eeda84062d40679651d0e3518a71bc",
                  "label":"",
                  "parentDynamicPanel":"e22b28cb8a1b415f995045c85668da13",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":84},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f707093a48f94a56819f43e4655f6803",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e22b28cb8a1b415f995045c85668da13",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":84},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"692f2f639bf045238eb1df6973a8f93b",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bece6914fb094f35b5002c1336086e8f",
                  "label":"",
                  "parentDynamicPanel":"e22b28cb8a1b415f995045c85668da13",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":302,
                      "height":106},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"82454605a8f5489daa172852d7b30034",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e22b28cb8a1b415f995045c85668da13",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":302,
                          "height":106},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/更换皮肤/u19.png"}},
{
                  "id":"1cae56e8e19c4f819415ca724707e65c",
                  "label":"",
                  "parentDynamicPanel":"e22b28cb8a1b415f995045c85668da13",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":273,
                      "y":77},
                    "size":{
                      "width":25,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b09629bf7404b639171caef5b4cb3c8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e22b28cb8a1b415f995045c85668da13",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":273,
                          "y":77},
                        "size":{
                          "width":25,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u35.png"}},
{
                  "id":"bd4f85a7b969492684a4dd0d2e2e684e",
                  "label":"",
                  "parentDynamicPanel":"e22b28cb8a1b415f995045c85668da13",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":9,
                      "y":82},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f546f87790dd4e3ebfdabc5de8a0bc50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e22b28cb8a1b415f995045c85668da13",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":9,
                          "y":82},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "f5b1649ffa8e4e6cb43830ac31088949":{
      "scriptId":"u0"},
    "4ae6c7ab622f4d10b6f8677472471d2c":{
      "scriptId":"u1"},
    "856b9fd391024a2d98e759fbbb90abcc":{
      "scriptId":"u2"},
    "f87f6ff5eddf4089abe0a0081a4acca2":{
      "scriptId":"u3"},
    "9b74b418f896400a8360a77ebba2aa21":{
      "scriptId":"u4"},
    "70c3b6a803d54b0d9f49b2f3597d0e19":{
      "scriptId":"u5"},
    "823e57666b1e4ad0b6be6b598ec85ee7":{
      "scriptId":"u6"},
    "2030c023edb44c178371b3792053c664":{
      "scriptId":"u7"},
    "fbda7572fee2454a812728b4bfdfc7a9":{
      "scriptId":"u8"},
    "abf3f148b81f4206b1854f5496ed0d0a":{
      "scriptId":"u9"},
    "193afac550884d93a417e36007e135a7":{
      "scriptId":"u10"},
    "b33250d6c98546b2af7de4dffc1f4794":{
      "scriptId":"u11"},
    "5150e5ccf0b94601a017b1ea54c68359":{
      "scriptId":"u12"},
    "c7f8ae26b75741b88cfbce49a26edd13":{
      "scriptId":"u13"},
    "57f9466e14974908ad9de4a4a5869188":{
      "scriptId":"u14"},
    "b28e07349b1b4522b03a04477f079032":{
      "scriptId":"u15"},
    "a6a4ebaba0ba4b4298b5dba38a5f6513":{
      "scriptId":"u16"},
    "2a8e872ef094480c8d53c9bdbaefb7f2":{
      "scriptId":"u17"},
    "3de57eac579244fca7b8e178b8aa1be3":{
      "scriptId":"u18"},
    "3c4eaf3670cc4b2b8a38b257506bdb57":{
      "scriptId":"u19"},
    "eef5e33687364bfd866bd31b864c53d4":{
      "scriptId":"u20"},
    "0cbd156558a04bc7a217a542b2b0cf83":{
      "scriptId":"u21"},
    "c4dd409cc51f4e8390d2dc9ead34d275":{
      "scriptId":"u22"},
    "2799cccd45e94c23b6a0423bcc5aa56d":{
      "scriptId":"u23"},
    "25441e26b3fd4a61befa475297a0703a":{
      "scriptId":"u24"},
    "2e11b440817d4582b9e1d974891f3e70":{
      "scriptId":"u25"},
    "4906a0325d774475b493d30340f7cf75":{
      "scriptId":"u26"},
    "5e8180be326045ecae6d23928df404eb":{
      "scriptId":"u27"},
    "0bbba94c868f4ea596546b2cec0bdef4":{
      "scriptId":"u28"},
    "65f8d43a43f14e279a43bd6aff63e1a6":{
      "scriptId":"u29"},
    "50a409a927ba44118193d332ac60eb2c":{
      "scriptId":"u30"},
    "244d0c3bf3a34cbaafe99bdf1efd23f6":{
      "scriptId":"u31"},
    "e538b82b16ca47af8cff283ca85dbdf5":{
      "scriptId":"u32"},
    "8be4430138a24d87a149d79f1a325dc6":{
      "scriptId":"u33"},
    "aacd5c8e3f9a4814a0f4a7c178406218":{
      "scriptId":"u34"},
    "c15e97e2ba514e79ac548832bba60d28":{
      "scriptId":"u35"},
    "ffa47afd980a43eaa0b2a884c8684f2d":{
      "scriptId":"u36"},
    "fe5f056bab504b4197641f55911fbea2":{
      "scriptId":"u37"},
    "e22b28cb8a1b415f995045c85668da13":{
      "scriptId":"u38"},
    "532df366b2de46f48ad7fcebf864483f":{
      "scriptId":"u39"},
    "4dc5f5704b6b4e149828624778e1dae5":{
      "scriptId":"u40"},
    "d3eeda84062d40679651d0e3518a71bc":{
      "scriptId":"u41"},
    "f707093a48f94a56819f43e4655f6803":{
      "scriptId":"u42"},
    "bece6914fb094f35b5002c1336086e8f":{
      "scriptId":"u43"},
    "82454605a8f5489daa172852d7b30034":{
      "scriptId":"u44"},
    "1cae56e8e19c4f819415ca724707e65c":{
      "scriptId":"u45"},
    "1b09629bf7404b639171caef5b4cb3c8":{
      "scriptId":"u46"},
    "bd4f85a7b969492684a4dd0d2e2e684e":{
      "scriptId":"u47"},
    "f546f87790dd4e3ebfdabc5de8a0bc50":{
      "scriptId":"u48"}}});