$axure.loadCurrentPage({
  "url":"家庭详情.html",
  "generationDate":new Date(1392634062088.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0707d844bd0640cb977925e12c1860e6",
    "type":"Axure:Page",
    "name":"家庭详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f837c2659bce4589baf7a3d8bb8789ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":0},
            "size":{
              "width":320,
              "height":530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6813c9d58ed5407da399b1e2e19409ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":0},
                "size":{
                  "width":320,
                  "height":530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/家庭详情/u0.png"}},
{
          "id":"dd77652837a545cb9fd59f50f06834ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":1},
            "size":{
              "width":319,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a850c8432c14434bb39d517b5ed6df10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":1},
                "size":{
                  "width":319,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u4.png"}},
{
          "id":"2a6dd5a681824bcd96b70693b88fb72f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":3,
              "y":20},
            "size":{
              "width":320,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b46dacb1fba5469f95f89a5668084d73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":3,
                  "y":20},
                "size":{
                  "width":320,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u106.png"}},
{
          "id":"5e4d37f7bcc74376850e34806c34e65e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":34},
            "size":{
              "width":37,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2c390c8ae2548dea6d8f45b1dc113ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":34},
                "size":{
                  "width":37,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13cf01402f0d4c0a871c42b130734fb6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":26},
            "size":{
              "width":32,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e08e752b541478788d8f905bce3ca7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":26},
                "size":{
                  "width":32,
                  "height":32},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u245.png"}},
{
          "id":"d061868f83f74152a54fb54f5fbf9178",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":77},
            "size":{
              "width":300,
              "height":115}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bd47c8d9fc541a384e4e704b6f73d08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":77},
                "size":{
                  "width":300,
                  "height":115}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/家庭详情/u10.png"}},
{
          "id":"642f1a5c3dbc4ba78bf4372c8b372c14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":88},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b1ee3120a2a4f40b013cc9587639a3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":88},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u88.png"}},
{
          "id":"ffa8d57c660141f9899f15a2414874b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"bold",
            "location":{
              "x":93,
              "y":88},
            "size":{
              "width":150,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2798abbd593c4a60a9d546d1f143a042",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"bold",
                "location":{
                  "x":93,
                  "y":88},
                "size":{
                  "width":150,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94079d9a49b2484e9d52c193431ba5ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":132},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"519a1567531442cc991fac0534e0fdbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":93,
                  "y":132},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50661310d72b40039e94d34d6cb0ae5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":21,
              "y":163},
            "size":{
              "width":284,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f599d817ba846188edda3ebe232d7d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":21,
                  "y":163},
                "size":{
                  "width":284,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b534a6b9d68a4129a950eb571b62e774",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":210},
            "size":{
              "width":300,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e4bc16ff18a4a27a3a28fa7007c79f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":210},
                "size":{
                  "width":300,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/家庭详情/u20.png"}},
{
          "id":"b4a6e30500f0425ab728bb51f6c9dbaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":216},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e9b4e890479409798d493c6b1c62f07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":216},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"c89fc1d836f54a5da266839dc7c834ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":75,
              "y":218},
            "size":{
              "width":138,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e88c97bedc0476d8470cf95e05f672b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":75,
                  "y":218},
                "size":{
                  "width":138,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6491af677e3b469581aa075324fc387c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":75,
              "y":246},
            "size":{
              "width":138,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a90ffe34a3442f98e37e80b9d777401",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":246},
                "size":{
                  "width":138,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2530107cf0854491b9a5736c0ee7813a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":271},
            "size":{
              "width":300,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22e1191c01b24e019eb092d1cbd1bc89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":271},
                "size":{
                  "width":300,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/家庭详情/u20.png"}},
{
          "id":"48057ad4225c48b6b05b916881e79c7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":277},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8e644d4d98f4427b80e97b17bee451a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":277},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"c1f95fb723984b2e89580d182b909ffb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":75,
              "y":279},
            "size":{
              "width":138,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9af97c96ae184dcba54c9ad8df591599",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":75,
                  "y":279},
                "size":{
                  "width":138,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"63911d9360a14aa48d590dce11bf48f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":75,
              "y":307},
            "size":{
              "width":138,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1951a37161ce4862879e73a2575f7c5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":307},
                "size":{
                  "width":138,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56bd257b121e4f0ba474ae26fac45a17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":332},
            "size":{
              "width":300,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc3d3faee909470096c261223e4478ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":332},
                "size":{
                  "width":300,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/家庭详情/u20.png"}},
{
          "id":"bd21d526e41349c48b8839f35322fd1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":338},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24b6c2a78b8042078f0e69aebc1eb212",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":338},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"b908169f546f46bc9fa73c0ba2945a76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":75,
              "y":340},
            "size":{
              "width":138,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"858206411b9b49ed9ea2b03936472546",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":75,
                  "y":340},
                "size":{
                  "width":138,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da37fe9cc43f4169a221cfa6818579ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":75,
              "y":368},
            "size":{
              "width":138,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dce2aaccd8f46afba40d7857c60ccb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":75,
                  "y":368},
                "size":{
                  "width":138,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0d4e63eebdd4ae5a24b46bd95444ab0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":253,
              "y":218},
            "size":{
              "width":54,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f26772b6f68c4e7d9a39c92ddd3338c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":253,
                  "y":218},
                "size":{
                  "width":54,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be69f36715a142c79151d091f21b0408",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":255,
              "y":338},
            "size":{
              "width":54,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c90b810234d844c4a35809d4274e008f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":255,
                  "y":338},
                "size":{
                  "width":54,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cb4caa237e944468af29d81830bbc1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":3,
              "y":20},
            "size":{
              "width":54,
              "height":43},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bec3486a474148c1b34c3c64d31d703d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":3,
                  "y":20},
                "size":{
                  "width":54,
                  "height":43},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5625fdb943c419a882621b336e15133",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":94,
              "y":113},
            "size":{
              "width":195,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8e99b73c3164ccaa51727d63c566d2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":94,
                  "y":113},
                "size":{
                  "width":195,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7838ec61645547b6bf6f2eee306bc4e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":393},
            "size":{
              "width":300,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7f5fcb1adaf41e295220b0a33b74d5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":393},
                "size":{
                  "width":300,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/家庭详情/u20.png"}},
{
          "id":"601e9413b2d74943b1a1a363aac8b755",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":399},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8851f31cbeae495b8cd6f010f1cfc9f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":399},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"44e50e283f6544af9b941ff59c33b150",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":272,
              "y":84},
            "size":{
              "width":30,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb4e0827a40c4e70addbcd038ca9f35f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":272,
                  "y":84},
                "size":{
                  "width":30,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 编辑",
                      "target":{
                        "targetType":"page",
                        "url":"编辑.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/家庭详情/u56.png"}},
{
          "id":"27d364afc0c64537966d88a1eb41a9f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":454},
            "size":{
              "width":300,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a268d20f0a0461d873cf331520919cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":454},
                "size":{
                  "width":300,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 添加家人",
                      "target":{
                        "targetType":"page",
                        "url":"添加家人.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/家庭详情/u20.png"}},
{
          "id":"d3c164e834a947798fc565d97e918910",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":460},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4f54caa8aab4880b06f259e8e5915bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":460},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u14.png"}},
{
          "id":"8e0dd1cc805a44458386f150c16ab184",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":19,
              "y":461},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7525ce03439b4900bcdbf8e6e167ffcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":19,
                  "y":461},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u62.png"}},
{
          "id":"a48716570ec646f0882eaf27346fc0d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":78,
              "y":474},
            "size":{
              "width":82,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01655c622e4741ea8dfe9da04a13058c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":474},
                "size":{
                  "width":82,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afa602823ee64629858abf8f2248c97c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":78,
              "y":403},
            "size":{
              "width":138,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a93a0e10ecbb4548905bf5bac9451bab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":78,
                  "y":403},
                "size":{
                  "width":138,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1567da263dbd403f9f5c96eeefcb727f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":251,
              "y":402},
            "size":{
              "width":54,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d056357f4fc9484aa9c9c4e279467445",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":251,
                  "y":402},
                "size":{
                  "width":54,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2030dd0399c845e093a4464b76f94970",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":78,
              "y":429},
            "size":{
              "width":138,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e7b332b09b14e008abca5d51097a3b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":78,
                  "y":429},
                "size":{
                  "width":138,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b83ad844f0147e890f7dd40d269eb72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":289,
              "y":229},
            "size":{
              "width":24,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c31872b77772434b9ab938fadb794b3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289,
                  "y":229},
                "size":{
                  "width":24,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"4fcee0c1dc05406082e4f40cab945aec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":288},
            "size":{
              "width":24,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94c3fea085114b678d8ef947d5cdeca1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":288},
                "size":{
                  "width":24,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"46664cda054045078c27e928b0b77cc1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":350},
            "size":{
              "width":24,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a90aee46abac4b1fb12fa51d9f427e06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":350},
                "size":{
                  "width":24,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"a11f5f87df34463a804b2f7537dfc497",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":288,
              "y":412},
            "size":{
              "width":24,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45a9bb8d0fed4a66b2320670aab388db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":288,
                  "y":412},
                "size":{
                  "width":24,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}},
{
          "id":"53b19456cc6a4a84b4eefa5c5fe7ca38",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":471},
            "size":{
              "width":24,
              "height":26},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66ec6662db444a4db8bb91049c054ecd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":471},
                "size":{
                  "width":24,
                  "height":26},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u42.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f837c2659bce4589baf7a3d8bb8789ff":{
      "scriptId":"u0"},
    "6813c9d58ed5407da399b1e2e19409ea":{
      "scriptId":"u1"},
    "dd77652837a545cb9fd59f50f06834ec":{
      "scriptId":"u2"},
    "a850c8432c14434bb39d517b5ed6df10":{
      "scriptId":"u3"},
    "2a6dd5a681824bcd96b70693b88fb72f":{
      "scriptId":"u4"},
    "b46dacb1fba5469f95f89a5668084d73":{
      "scriptId":"u5"},
    "5e4d37f7bcc74376850e34806c34e65e":{
      "scriptId":"u6"},
    "b2c390c8ae2548dea6d8f45b1dc113ad":{
      "scriptId":"u7"},
    "13cf01402f0d4c0a871c42b130734fb6":{
      "scriptId":"u8"},
    "7e08e752b541478788d8f905bce3ca7a":{
      "scriptId":"u9"},
    "d061868f83f74152a54fb54f5fbf9178":{
      "scriptId":"u10"},
    "0bd47c8d9fc541a384e4e704b6f73d08":{
      "scriptId":"u11"},
    "642f1a5c3dbc4ba78bf4372c8b372c14":{
      "scriptId":"u12"},
    "7b1ee3120a2a4f40b013cc9587639a3c":{
      "scriptId":"u13"},
    "ffa8d57c660141f9899f15a2414874b2":{
      "scriptId":"u14"},
    "2798abbd593c4a60a9d546d1f143a042":{
      "scriptId":"u15"},
    "94079d9a49b2484e9d52c193431ba5ce":{
      "scriptId":"u16"},
    "519a1567531442cc991fac0534e0fdbd":{
      "scriptId":"u17"},
    "50661310d72b40039e94d34d6cb0ae5f":{
      "scriptId":"u18"},
    "3f599d817ba846188edda3ebe232d7d2":{
      "scriptId":"u19"},
    "b534a6b9d68a4129a950eb571b62e774":{
      "scriptId":"u20"},
    "2e4bc16ff18a4a27a3a28fa7007c79f7":{
      "scriptId":"u21"},
    "b4a6e30500f0425ab728bb51f6c9dbaf":{
      "scriptId":"u22"},
    "8e9b4e890479409798d493c6b1c62f07":{
      "scriptId":"u23"},
    "c89fc1d836f54a5da266839dc7c834ae":{
      "scriptId":"u24"},
    "8e88c97bedc0476d8470cf95e05f672b":{
      "scriptId":"u25"},
    "6491af677e3b469581aa075324fc387c":{
      "scriptId":"u26"},
    "8a90ffe34a3442f98e37e80b9d777401":{
      "scriptId":"u27"},
    "2530107cf0854491b9a5736c0ee7813a":{
      "scriptId":"u28"},
    "22e1191c01b24e019eb092d1cbd1bc89":{
      "scriptId":"u29"},
    "48057ad4225c48b6b05b916881e79c7e":{
      "scriptId":"u30"},
    "e8e644d4d98f4427b80e97b17bee451a":{
      "scriptId":"u31"},
    "c1f95fb723984b2e89580d182b909ffb":{
      "scriptId":"u32"},
    "9af97c96ae184dcba54c9ad8df591599":{
      "scriptId":"u33"},
    "63911d9360a14aa48d590dce11bf48f0":{
      "scriptId":"u34"},
    "1951a37161ce4862879e73a2575f7c5f":{
      "scriptId":"u35"},
    "56bd257b121e4f0ba474ae26fac45a17":{
      "scriptId":"u36"},
    "cc3d3faee909470096c261223e4478ca":{
      "scriptId":"u37"},
    "bd21d526e41349c48b8839f35322fd1e":{
      "scriptId":"u38"},
    "24b6c2a78b8042078f0e69aebc1eb212":{
      "scriptId":"u39"},
    "b908169f546f46bc9fa73c0ba2945a76":{
      "scriptId":"u40"},
    "858206411b9b49ed9ea2b03936472546":{
      "scriptId":"u41"},
    "da37fe9cc43f4169a221cfa6818579ee":{
      "scriptId":"u42"},
    "2dce2aaccd8f46afba40d7857c60ccb6":{
      "scriptId":"u43"},
    "b0d4e63eebdd4ae5a24b46bd95444ab0":{
      "scriptId":"u44"},
    "f26772b6f68c4e7d9a39c92ddd3338c9":{
      "scriptId":"u45"},
    "be69f36715a142c79151d091f21b0408":{
      "scriptId":"u46"},
    "c90b810234d844c4a35809d4274e008f":{
      "scriptId":"u47"},
    "5cb4caa237e944468af29d81830bbc1d":{
      "scriptId":"u48"},
    "bec3486a474148c1b34c3c64d31d703d":{
      "scriptId":"u49"},
    "f5625fdb943c419a882621b336e15133":{
      "scriptId":"u50"},
    "a8e99b73c3164ccaa51727d63c566d2a":{
      "scriptId":"u51"},
    "7838ec61645547b6bf6f2eee306bc4e4":{
      "scriptId":"u52"},
    "c7f5fcb1adaf41e295220b0a33b74d5c":{
      "scriptId":"u53"},
    "601e9413b2d74943b1a1a363aac8b755":{
      "scriptId":"u54"},
    "8851f31cbeae495b8cd6f010f1cfc9f6":{
      "scriptId":"u55"},
    "44e50e283f6544af9b941ff59c33b150":{
      "scriptId":"u56"},
    "bb4e0827a40c4e70addbcd038ca9f35f":{
      "scriptId":"u57"},
    "27d364afc0c64537966d88a1eb41a9f2":{
      "scriptId":"u58"},
    "7a268d20f0a0461d873cf331520919cf":{
      "scriptId":"u59"},
    "d3c164e834a947798fc565d97e918910":{
      "scriptId":"u60"},
    "b4f54caa8aab4880b06f259e8e5915bf":{
      "scriptId":"u61"},
    "8e0dd1cc805a44458386f150c16ab184":{
      "scriptId":"u62"},
    "7525ce03439b4900bcdbf8e6e167ffcf":{
      "scriptId":"u63"},
    "a48716570ec646f0882eaf27346fc0d0":{
      "scriptId":"u64"},
    "01655c622e4741ea8dfe9da04a13058c":{
      "scriptId":"u65"},
    "afa602823ee64629858abf8f2248c97c":{
      "scriptId":"u66"},
    "a93a0e10ecbb4548905bf5bac9451bab":{
      "scriptId":"u67"},
    "1567da263dbd403f9f5c96eeefcb727f":{
      "scriptId":"u68"},
    "d056357f4fc9484aa9c9c4e279467445":{
      "scriptId":"u69"},
    "2030dd0399c845e093a4464b76f94970":{
      "scriptId":"u70"},
    "1e7b332b09b14e008abca5d51097a3b5":{
      "scriptId":"u71"},
    "8b83ad844f0147e890f7dd40d269eb72":{
      "scriptId":"u72"},
    "c31872b77772434b9ab938fadb794b3c":{
      "scriptId":"u73"},
    "4fcee0c1dc05406082e4f40cab945aec":{
      "scriptId":"u74"},
    "94c3fea085114b678d8ef947d5cdeca1":{
      "scriptId":"u75"},
    "46664cda054045078c27e928b0b77cc1":{
      "scriptId":"u76"},
    "a90aee46abac4b1fb12fa51d9f427e06":{
      "scriptId":"u77"},
    "a11f5f87df34463a804b2f7537dfc497":{
      "scriptId":"u78"},
    "45a9bb8d0fed4a66b2320670aab388db":{
      "scriptId":"u79"},
    "53b19456cc6a4a84b4eefa5c5fe7ca38":{
      "scriptId":"u80"},
    "66ec6662db444a4db8bb91049c054ecd":{
      "scriptId":"u81"}}});